### ISSUE TITLE
ibm.power_aix.user  fails to create/modify user with space in gecos

### ISSUE THREAD

**Issue by hyperrustie** [IBM/ansible-power-aix#151]
**Describe the bug**
Create or modify user fails if gecos contains spaces

**To Reproduce**
example play

    - name: Create user test1
      ibm.power_aix.user:
        state: present
        name: test1
        attributes:
          gecos: "Test1"

    - name: Create user test2
      ibm.power_aix.user:
        state: present
        name: test2
        attributes:
          gecos: "Test2 User for testing gecos"

**Expected behavior**
both users are created with specified gecos

**Output**

    TASK [Create user test1]
 
 
 
 ********************************************************************************************************************************************************************************************
    task path: /home/user/projects/Ansible/PowerPlay/roles/test/tasks/main.yml:4
    changed: [myhost.mydomain] => {"changed": true, "msg": "Username is created SUCCESSFULLY: test1"}

    TASK [Create user test2] 
 
 
 
 ********************************************************************************************************************************************************************************************
    task path: /home/user/projects/Ansible/PowerPlay/roles/test/tasks/main.yml:11
    fatal: [myhost.mydomain]: FAILED! => {"changed": false, "msg": "Failed to create user: test2", "rc": 22, "stderr": "Usage: mkuser [-R load_module] [-a] \"attr=value\" ... newuser\n", "stderr_lines": ["Usage: mkuser [-R load_module] [-a] \"attr=value\" ... newuser"], "stdout": "", "stdout_lines": []}

    PLAY RECAP 
 
 
 
 **********************************************************************************************************************************************************************************************************
    myhost.mydomain     : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

**Environment (please complete the following information):**
cat MANIFEST.json 
{
 "collection_info": {
  "namespace": "ibm",
  "name": "power_aix",
  "version": "1.3.1",
  "authors": [
   "Paul B. Finley (@pbfinley1911)"
  ],

ansible 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/de50870/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]

**Comment by stephenulmer** [comment]
I have a fix for this in a local branch. I'll try and get it rebased for the current HEAD and create a PR.

**Comment by pvtorres** [comment]
Closing the issue. We merged Stephen pull request with the fix for this problem.

**Comment by hyperrustie** [comment]
Thx @stephenulmer for fixing this one. picked and tested.

**Comment by StevePOI** [comment]
Hello!

I´m still getting an error using the ibm.power_aix.user Module to modify an attribute:

```
---

- name: Change a user attribute 
  hosts: MYSERVER 
  become: true
  gather_facts: true 
  collections:
     - ibm.power_aix
  vars:
   USER: MYUSER # e.g. root
   ATTR: pwdwarntime # with or without quotation or as a variable coming via -e flag
   VAL: 0 # with or without quotation or as a variable coming via -e flag
  tasks:

   - debug:
      msg: "{{ USER }} bekommt bei {{ ATTR }} den Wert {{ VAL }}"

   - name: Change the attribute
     user: 
      state: modify
      name: "{{ USER }}"
      attributes:
       "{{ ATTR }}": "{{ VAL }}"

```
leads to:

```
debug...
  MYSERVER ok: {
    "changed": false,
    "msg": "MYUSER bekommt bei pwdwarntime den Wert 0"
}
Change the attribute...
  MYSERVER failed: {
    "changed": false,
    "msg": "\nFailed to modify attributes for the user: MYUSER",
    "rc": 22,
    "stderr": "Usage: chuser [-R load_module] \"attr=value\" ... user\n",
    "stderr_lines": [
        "Usage: chuser [-R load_module] \"attr=value\" ... user"
    ],
    "stdout": "",
    "stdout_lines": []
}

```

This of course works:

```
---                   
                      
- name: Change a user attribute 
  hosts: all          
  become: true        
  gather_facts: true  
  collections:        
     - ibm.power_aix  
  tasks:              
                      
   - name: Change the attribute
     user:            
      state: modify   
      name: MYUSER         
      attributes:        
        pwdwarntime: 0                 
```
Result:

```
Change the attribute...
  MYSERVER done: {
    "changed": true,
    "msg": "\nAll provided attributes for the user: MYUSER are set SUCCESSFULLY"
}
```

What can be the problem with the variables here? Also not the first issue with the user/group module, ran into the one with password and GECOS as well....

Thanks!
