### ISSUE TITLE
modul filesystem is not idempotent when using jfs2 attribute agblksize

### ISSUE THREAD

**Issue by pc2306** [IBM/ansible-power-aix#402]
**Describe the bug**
When using jfs2 attribute _agblksize_, the first call of the module successfully creates the filesystem with _crfs_, but subsequent calls fail, since this attribute cannot be used with _chfs_ command.

**To Reproduce**
Add the following task to a playbook:

```
- name: Creation of a JFS2 filesystem
  ibm.power_aix.filesystem:
    state: present
    filesystem: /mnt3
    fs_type: jfs2
    attributes: size=32768,isnapshot='no',agblksize=512
    mount_group: test
    vg: rootvg
```

**Expected behavior**
On subsequent calls it should not fail when calling _chfs_.

**Comment by nitismis** [comment]
thanks for reporting. We are working on it.

**Comment by rseabra** [comment]
How is state 'modify' something compatible with the concept of idempotency?

**Comment by schamola** [comment]
Hi @rseabra 
In #424 this issue was fixed without the use of state 'modify'
Can you confirm if it is working as per your expectations now ?

**Comment by pc2306** [comment]
Hi @schamola,
I'm afraid your change will not fix the issue. So you can better understand my problem, let me show you an example.
The first call of
```
- name: Creation of a JFS2 filesystem
  ibm.power_aix.filesystem:
    state: present
    filesystem: /mnt3
    fs_type: jfs2
    attributes: size=32768,isnapshot='no',agblksize=512
    mount_group: test
    vg: rooting
```
will create the filesystem. With your fix, repeating calls will fail, although nothing has changed, since agblksize ist not allowed with chfs. This behaviour is contrary to the concept of idempotency.

When I change the size attribute like this:
```
- name: Creation of a JFS2 filesystem
  ibm.power_aix.filesystem:
    state: present
    filesystem: /mnt3
    fs_type: jfs2
    attributes: size=65536,isnapshot='no',agblksize=512
    mount_group: test
    vg: rooting
```
I would expect the module to change just the size of the filesystem. But once again it will return an error because of the attribute agblksize.

So instead of returning an error when there are attributes like agblksize, these attributes should just be ignored when calling the chfs command.

I hope this sheds some light on my problem.

Thanks and best regards

**Comment by rseabra** [comment]
@schamola the problem exists with state: present, it tries to modify for some mysterious and incorrect reason, and then invokes chfs incorrectly. So it's like two bugs in one, cheaper by the dozen. :)

**Comment by schamola** [comment]
@rseabra thanks for the elaboration.
We will fix it, soon !

**Comment by schamola** [comment]
Hi @rseabra , 
We have pushed the fix for this issue. Please check and confirm if it is working fine for you now.

**Comment by nitismis** [comment]
@rseabra,  We have merged the fix. Please reopen this issue if it does not address your problem.

**Comment by rseabra** [comment]
@schamola @nitismis 

This is not fixed, it continues to "change" the filesystems.
I run once it creates, I run it again and it "changes" something (since no passed parameter changed, nothing should have changed, which means **idempotency is not working yet**).

It seems to have fixed only the chfs invocation, but not the **required** idempotency :)

**Comment by rseabra** [comment]
This is the task:
```yaml
- name: Setup DATA Filesystems
  ibm.power_aix.filesystem:
    attributes: "{{ item.1.attributes|default(omit) }}"
    auto_mount: "{{ item.1.auto_mount|default(true) }}"
    device: "{{ item.1.lv }}"
    filesystem: "{{ item.1.filesystem|default(item.1.mount) }}"
    fs_type: "{{ item.1.fs|default('jfs2') }}"
    permissions: "{{ item.1.permissions|default('rw') }}"
    state: "{{ item.1.state|default('present') }}"
  loop: "{{ datavgs|subelements('lvs') }}"
  when: "item.1.mountfs|default(true)"
  tags:
  - datavg-fs
```

And this is the relevant inventory variable:
```yaml
            datavgs:
              - vg: "datavg"
                lvs:
                - { lv: "fs1lv",            size: "2G", mount: "/opt/fs1" }
                - { lv: "fs2lv",                size: "2G", mount: "/opt/fs2" }
```

**Comment by schamola** [comment]
Hi @rseabra,
Thanks for providing the extra information, It helped us in analysing the issue properly.

We have fixed the issue, it should be working for you now. Let us know once you verify.

**Comment by schamola** [comment]
Hi @rseabra !
Just a gentle reminder, can you please confirm if the module is working for you now ?

If yes, we will close this defect.
