### ISSUE TITLE
demo_flrtvc_local_patch_server.yml installing in random order and choosing VIOS instead of AIX eFIX

### ISSUE THREAD

**Issue by th-burghardt** [IBM/ansible-power-aix#609]
Hi, 

in the process of implementing the flrtvc Module, the installation of Fixes differs each run it is executed. 
Some Fixes will be installed as VIOS-Fix instead of the corresponding AIX-Fix. 

Shouldn't be the order the same and if multiple kernel_fixes are avaibale, shouldn't the latest be installed? 
I am using a local-patchserver, which was created using: demo_shell_flrtvc_wget_ifix.yml

Target:
AIX: 
7200-05-04-2220
python3-3.9.19-1.ppc

Ansible-Node:
ansible core 2.5.19
ibm.power_aix 2.0.2
Python 3.9.20

1st run:
> emgr -l

ID  STATE LABEL      INSTALL TIME      UPDATED BY ABSTRACT
=== ===== ========== ================= ========== ======================================
1    S    IJ48252s6a 02/02/25 18:50:26            IJ48252 POTENTIAL SECURITY ISSUE      
2    S    IJ44425m4b 02/02/25 18:50:32            IJ44425 POTENTIAL SECURITY ISSUE      
3   *Q*   IJ50937m2a 02/02/25 18:50:42            IJ50937 POTENTIAL SECURITY ISSUE      
4    S    IJ45056m4a 02/02/25 18:50:50            IJ45056 POTENTIAL SECURITY ISSUE      
5    S    81112ma    02/02/25 18:51:01            ifix for openssh Jan CVEs             
6   *Q*   IJ49533m4a 02/02/25 18:51:23            IJ49533 POTENTIAL SECURITY ISSUE      
7   *Q*   IJ49534s3a 02/02/25 18:51:30            IJ49534 POTENTIAL SECURITY ISSUE      
8    S    IJ42677s4a 02/02/25 18:51:34            IJ42677 POTENTIAL SECURITY ISSUE      
9    S    IJ49461m2c 02/02/25 18:51:45            IJ49461 POTENTIAL SECURITY ISSUE      
10   S    IJ42163m4a 02/02/25 18:52:09            IJ42163 POTENTIAL SECURITY ISSUE      
11   S    IJ45245s4a 02/02/25 18:52:16            IJ45245 POTENTIAL SECURITY ISSUE      
**12   S    IJ50508s1a 02/02/25 18:52:25            IJ50508 for VIOS 3.1.3.30 and 3.1.3.40**
13  *Q*   IJ43876s3a 02/02/25 18:52:33            IJ43876 POTENTIAL SECURITY ISSUE      

2nd run:
> emgr -l

ID  STATE LABEL      INSTALL TIME      UPDATED BY ABSTRACT
=== ===== ========== ================= ========== ======================================
1    S    IJ48252s6a 02/03/25 07:40:52            IJ48252 POTENTIAL SECURITY ISSUE      
2    S    IJ50828m4a 02/03/25 07:40:56            IJ50828 POTENTIAL SECURITY ISSUE      
3    S    81112ma    02/03/25 07:41:07            ifix for openssh Jan CVEs             
4    S    IJ42677s4a 02/03/25 07:41:28            IJ42677 POTENTIAL SECURITY ISSUE      
5   *Q*   IJ41974s4a 02/03/25 07:41:32            IJ41974 POTENTIAL SECURITY ISSUE      
6   *Q*   IJ42159s4a 02/03/25 07:41:38            IJ42159 POTENTIAL SECURITY ISSUE      
7   *Q*   IJ43869m4a 02/03/25 07:41:46            IJ43869 POTENTIAL SECURITY ISSUE      
8   *Q*   IJ43876s3a 02/03/25 07:41:51            IJ43876 POTENTIAL SECURITY ISSUE      
9    S    IJ42163m4a 02/03/25 07:41:55            IJ42163 POTENTIAL SECURITY ISSUE      
**10   S    IJ50508s1a 02/03/25 07:42:00            IJ50508 for VIOS 3.1.3.30 and 3.1.3.40**
11   S    IJ40615m4b 02/03/25 07:42:10            IJ40615 for AIX 7.2 TL5 SP2 SP4       
12   S    IJ49461m2c 02/03/25 07:42:25            IJ49461 POTENTIAL SECURITY ISSUE      
13   S    IJ45245s4a 02/03/25 07:42:52            IJ45245 POTENTIAL SECURITY ISSUE      
14  *Q*   IJ49534s3a 02/03/25 07:43:01            IJ49534 POTENTIAL SECURITY ISSUE      

And following messages:
                "a previous efix to install will lock a file of IJ43218s4a.221227.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ43869m4b.230216.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ43876s4a.221017.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of 38408m9b.230811.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ47597m4a.230718.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ47632m4a.230718.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ42339s4a.220907.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ42379s4a.220909.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ50937m2a.240502.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ44425m4b.230217.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ41685s4a.220809.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ44424s5.221129.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ49094s4.231110.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ39876s3a.220506.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ45056m4a.230125.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ45058m4a.230125.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ45058m4b.230405.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ42162m4a.221208.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ44559m4a.221214.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ46051s2a.230323.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ49202m2a.231219.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ49202m2b.240109.epkg.Z preventing its installation, install it manually or run the task again.",
                "a previous efix to install will lock a file of IJ49533m4a.231219.epkg.Z preventing its installation, install it manually or run the task again."

**Comment by nitismis** [comment]
Hi @th-burghardt,
We have not made any recent changes in the flrtvc module but there are around 5 open defects for this module. We are working with flrtvc team because in the module there script is used. We are on it.
BTW, I see your ansible-core version is bit old.

**Comment by th-burghardt** [comment]
Hi, thanks - I assume the part: 
`# sort the epkg by packing date (sec from epoch) `
does not work correctly ot something else doing the tasks regardings packing date.

In example, the fix IJ50828m4a from libxml2_fix6 will not be installed because IJ47597m4a from libxml2_fix5 will be installed first, even the packing dates should prevent it. 

LABEL:            IJ47597m4a
PACKAGING DATE:   Tue Jul 18 11:55:27 CDT 2023

LABEL:            IJ50828m4a
PACKAGING DATE:   Tue Apr  9 11:26:23 CDT 2024

**Comment by schamola** [comment]
Hi @th-burghardt 
Thanks for pointing out the sorting issue, we have fixed that part. Please confirm if it's working fine for you now.

About the VIOS fixes, we are working with the broader team to fix it. Will let you know of any updates !

**Comment by th-burghardt** [comment]
Hi, the sorting seems to work, the check from the flrtvc.ksh script itslef does not work like a charme, since it will report a lot of fixes that are not fixed because it may not analyze the part "This iFix also includes:" in a newer iFix.
